Feature/tab name change
pritipsingh/The-Productive-Champion pull request #32
Opened 2024-07-16 11:14 UTC by 02-ahmed

Addresses the feature request of adding "Focus Mode & Disable Notifications" to the tab name of blocked sites.

# Closes #27

2024-07-20 07:54 UTC, pritipsingh requested changes

2024-07-20 07:54 UTC, pritipsingh commented on my-extension/src/components/Restrict.tsx
> +          flexDirection:"column", //added flex direction column because i moved the random message inside this div
we don't need the comment here

2024-07-20 07:54 UTC, pritipsingh commented on my-extension/src/components/Restrict.tsx
> +          style={{maxHeight:"500px"}} //set max height of gif to 500px so it doesn't push the random message out of the view height
again comment not needed

2024-07-20 07:54 UTC, pritipsingh commented on my-extension/src/components/Restrict.tsx
> +        </h3> {/* moved the h3 tag inside the div that contains the image to ensure that the random message is always underneath the gif */}
this too

2024-07-20 07:54 UTC, pritipsingh commented on my-extension/src/components/WebsiteEditPage.tsx
> +      setSlreadyBlockedWebsitesSet(alreadyBlockedWebsites); // Assuming 'alreadyBlockedWebsites' is an array
these comments are fine

2024-07-20 07:54 UTC, pritipsingh commented on my-extension/src/components/WebsiteEditPage.tsx
> +      }, []); //this was different from the code in the deployment so copied the deployed code back which caused the edit websites to block to start working again
not needed please remove

2024-07-20 07:54 UTC, pritipsingh commented on my-extension/src/content/index.tsx
> +//content script was running multiple times so added code to check if the restrict component is already rendered before adding a new one
not needed

2024-07-20 07:54 UTC, pritipsingh commented on my-extension/src/content/index.tsx
> +  document.title += ` | Focus Mode & Disable Notifications` //appended the text to the existing tab name by using tempelate literals to ensure the white spaces take effect
this is fine but make it shorter

2024-07-20 07:54 UTC, pritipsingh commented on my-extension/src/components/Restrict.tsx
> +          style={{maxHeight:"500px"}} //set max height of gif to 500px so it doesn't push the random message out of the view height
any reason to particularly use px and not rem or vh

2024-07-20 08:26 UTC, 02-ahmed commented on my-extension/src/components/Restrict.tsx
> +          style={{maxHeight:"500px"}} //set max height of gif to 500px so it doesn't push the random message out of the view height
no particular reason
changed it to use vh

2024-07-20 09:14 UTC, pritipsingh commented
Thanks for the contributions @02-ahmed ! If you ever have your sponsor button enabled, feel free to email me. Would love to support you in your OS journey.

2024-07-20 09:14 UTC, merged

2024-07-20 09:18 UTC, 02-ahmed commented
Thank You Priti

Glad to have been able contribute
I would like to reach out if i need guidance or if i encounter any
challenges I need help with
Where can i reach you more easily ?

Thanks again


On Sat, 20 Jul 2024 at 09:15, Priti ***@***.***> wrote:

> Merged #32
> <https://github.com/pritipsingh/The-Productive-Champion/pull/32> into
> main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pritipsingh/The-Productive-Champion/pull/32#event-13588835845>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5MV6R3AYCMM47JRSGHSSHTZNITBXAVCNFSM6AAAAABK6LUTVKVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJTGU4DQOBTGU4DINI>
> .
> You are receiving this because you were mentioned.Message ID:
> <pritipsingh/The-Productive-Champion/pull/32/issue_event/13588835845@
> github.com>
>

2024-10-04 10:28 UTC, 02-ahmed commented
Hello Pritipriya,

Trust you are well
I noticed that my pull requests that you merged a while back have not been
deployed. So the bugs that are supposed to be resolved are still there when
you install the extension from the chrome store.
I have noticed another bug that I would like to work on so if you can check
the deployment issue out that would be great.
Is there a social media you're comfortable with? so I can be reaching out
more easily

Also, my github sponsor button is enabled now

Hoping to hear from you soon

Best regards,
Ahmed

On Sat, 20 Jul 2024 at 09:15, Priti ***@***.***> wrote:

> Thanks for the contributions @02-ahmed <https://github.com/02-ahmed> ! If
> you ever have your sponsor button enabled, feel free to email me. Would
> love to support you in your OS journey.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pritipsingh/The-Productive-Champion/pull/32#issuecomment-2241055492>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5MV6R3KC764NZFRIZNCB2TZNITBNAVCNFSM6AAAAABK6LUTVKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENBRGA2TKNBZGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-23 10:58 UTC, 02-ahmed commented
Hello Pritipriya,

Trust you are well
I noticed that my pull requests that you merged a while back have not been
deployed. So the bugs that are supposed to be resolved are still there when
you install the extension from the chrome store.
I have noticed another bug that I would like to work on so if you can check
the deployment issue out that would be great

Also, my github sponsor button is enabled now

Hoping to hear from you soon

Best regards,
Ahmed


On Sat, 20 Jul 2024 at 09:15, Priti ***@***.***> wrote:

> Thanks for the contributions @02-ahmed <https://github.com/02-ahmed> ! If
> you ever have your sponsor button enabled, feel free to email me. Would
> love to support you in your OS journey.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pritipsingh/The-Productive-Champion/pull/32#issuecomment-2241055492>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5MV6R3KC764NZFRIZNCB2TZNITBNAVCNFSM6AAAAABK6LUTVKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENBRGA2TKNBZGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>